resteasy:
  jaxrs:
    app:
      registration: property
      classes: comments.main.CommentsAPIApplication
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - shutdown
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    org:
      springframework: info